// <auto-generated />
namespace Proj_SuperMarket.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class salesdb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(salesdb));
        
        string IMigrationMetadata.Id
        {
            get { return "202206150804057_salesdb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
